import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Focus, Languages, ShieldCheck } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
export const metadata: Metadata = { title: "عن سياق" };
<<<<<<< HEAD
export default function AboutPage() { return <main><SiteHeader /><section className="about-hero shell" data-reveal><span className="eyebrow"><span className="eyebrow-line" /> عن سياق</span><h1>الأداة الجيدة<br />تختفي خلف النتيجة.</h1><p>بدأ سياق من سؤال بسيط: لماذا تحتاج مهمة صغيرة على ملف إلى واجهة مزدحمة وشرح طويل؟</p></section><section className="about-principles shell" data-reveal><article><Focus size={26} /><span>01</span><h2>المهمة أولًا</h2><p>نضع الأداة ومساحة الرفع قبل الخيارات الثانوية.</p></article><article><Languages size={26} /><span>02</span><h2>عربي من البداية</h2><p>الاتجاه والنص والمسافات مصممة لتجربة عربية طبيعية.</p></article><article><ShieldCheck size={26} /><span>03</span><h2>الثقة قابلة للفهم</h2><p>نوضح حالة الأداة وحدود الملفات وما يحدث بعد الرفع.</p></article></section><section className="about-story" data-reveal><div className="shell"><div><span>سياق / getsiaq.com</span><h2>مساحة عربية تجعل التعامل مع الملفات أبسط.</h2></div><p>نجمع المهام المتكررة في أدوات واضحة، ونرتبها حسب النتيجة التي تريدها حتى تصل من الملف إلى النسخة الجاهزة بثقة وخطوات أقل.</p></div></section><section className="about-cta shell" data-reveal><h2>ابدأ بما تريد إنجازه.</h2><Link href="/tools">كل الأدوات <ArrowLeft size={17} /></Link></section><SiteFooter /></main>; }
=======
export default function AboutPage() { return <main><SiteHeader /><section className="about-hero shell"><span className="eyebrow"><span className="eyebrow-line" /> عن سياق</span><h1>الأداة الجيدة<br />تختفي خلف النتيجة.</h1><p>بدأ سياق من سؤال بسيط: لماذا تحتاج مهمة صغيرة على ملف إلى واجهة مزدحمة وشرح طويل؟</p></section><section className="about-principles shell"><article><Focus size={26} /><span>01</span><h2>المهمة أولًا</h2><p>نضع الأداة ومساحة الرفع قبل التسويق والخيارات الثانوية.</p></article><article><Languages size={26} /><span>02</span><h2>عربي من البداية</h2><p>ليست ترجمة لاحقة؛ الاتجاه والنص والمسافات مصممة للعربية.</p></article><article><ShieldCheck size={26} /><span>03</span><h2>الثقة قابلة للفهم</h2><p>نوضح حالة المحرك وحدود الملفات وما يحدث بعد الرفع.</p></article></section><section className="about-story"><div className="shell"><div><span>سياق / getsiaq.com</span><h2>منصة ملفات مستقلة بواجهة Next.js ومحرك Django.</h2></div><p>نبني الأدوات على مراحل قابلة للاختبار، ونفصل الواجهة عن المعالجة حتى يمكن توسيع المحرك وتأمينه دون تعقيد تجربة المستخدم.</p></div></section><section className="about-cta shell"><h2>ابدأ بما تريد إنجازه.</h2><Link href="/tools">كل الأدوات <ArrowLeft size={17} /></Link></section><SiteFooter /></main>; }
>>>>>>> 7c02a53d332ebcf3c6c714e955d1d83dfd1aab40
